In [1]:
import operators as op
import numpy as np

#adj = np.array([[0, 1, 0, 0],[1, 0, 1, 0],[0, 1, 0, 1],[0, 0, 1, 0]])
adj = np.array([[0, 1, 1, 1],
                [1, 0, 1, 0],
                [1, 1, 0, 0],
                [1, 0, 0, 0]])              

L_R = op.compute_laplacian(adj,1)
L_A = op.compute_laplacian(adj,-1)
L = op.compute_laplacian(adj,0)

print("Hubs-attracting Laplacian matrix L_A:")
print(L_A)

print("Laplacian matrix L")
print(L)

print("Hubs-repelling Laplacian matrix L_R:")
print(L_R)


Hubs-attracting Laplacian matrix L_A:
[[ 1.66666667 -0.66666667 -0.66666667 -0.33333333]
 [-1.5         2.5        -1.          0.        ]
 [-1.5        -1.          2.5         0.        ]
 [-3.          0.          0.          3.        ]]
Laplacian matrix L
[[ 3 -1 -1 -1]
 [-1  2 -1  0]
 [-1 -1  2  0]
 [-1  0  0  1]]
Hubs-repelling Laplacian matrix L_R:
[[ 6.         -1.5        -1.5        -3.        ]
 [-0.66666667  1.66666667 -1.          0.        ]
 [-0.66666667 -1.          1.66666667  0.        ]
 [-0.33333333  0.          0.          0.33333333]]
